[package]
name = "mat/alloy"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
fusion = "elttob/fusion@0.3.0"

[server-dependencies]